development:
  adapter: postgresql
  encoding: unicode
  database: shakeventure_development
  host: localhost
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: shakeventure_test
  host: localhost
  pool: 5
  username: 
  password: 